"""
Week 1 - Day 4

Topic:
Structured Outputs using JSON Mode + Pydantic

This script demonstrates how to extract structured
information from an unstructured customer support ticket
using an LLM.

Instead of receiving plain text, the model is instructed
to return a valid JSON object which is then validated
using Pydantic.

Author : Mayank
"""

import os
from dotenv import load_dotenv
from groq import Groq

# --------------------------------------------------------
# STEP 1: Load environment variables from the .env file
# This keeps sensitive information like API keys outside the source code.
# --------------------------------------------------------

load_dotenv()


# Retrieve the API key from environment variables.
my_api_key = os.getenv("GROQ_API_KEY")


# Stop execution if the API key is missing.
if not my_api_key:
    raise ValueError ("GROQ_API_KEY not found. Please check your .env file.")



# --------------------------------------------------------
# STEP 2: Create the Groq client
# This client will be used to communicate with the LLM.
# --------------------------------------------------------
client = Groq(api_key = my_api_key)

# Selecting the language model for response.
model = "llama-3.3-70b-versatile"

role = "user"


# --------------------------------------------------------
# STEP 3: Define the Output Schema using Pydantic
#
# Pydantic allows us to define the exact structure that
# the LLM should return.
#
# Instead of receiving random text, we expect a JSON
# object containing:
#   - name
#   - email
#   - issue
#
# This makes the output machine-readable and easy to
# validate before using it in production applications.
# --------------------------------------------------------

from pydantic import BaseModel

class Ticket(BaseModel):
    name: str
    email: str
    issue: str

# Convert the Pydantic model into a JSON schema.
schema = Ticket.model_json_schema()


# --------------------------------------------------------
# STEP 4: Enable JSON Mode
#
# JSON mode forces the LLM to return a valid JSON object
# instead of normal conversational text.
#
# Without this, the model may return paragraphs,
# bullet points or markdown which are difficult to parse.
# --------------------------------------------------------
response_format = {
    "type": "json_object"
}

# --------------------------------------------------------
# STEP 5: Create the System Prompt
#
# The system prompt defines the behaviour of the model.
#
# Here we provide the JSON schema and explicitly instruct
# the model to strictly follow it.
#
# IMPORTANT:
# Groq requires the word "JSON" to appear somewhere in
# the messages whenever response_format=json_object is
# used, otherwise it throws a BadRequestError.
# --------------------------------------------------------

system_prompt = f"""
Extract the personal information from the ticket strictly based on this schema and give a json output.

{schema}
"""

message_system = {
    "role": "system",
    "content": system_prompt
}


# --------------------------------------------------------
# STEP 6: Customer Support Ticket
#
# This represents an unstructured customer message.
#
# Notice that it contains extra information such as
# location and phone number.
#
# Since these fields are NOT present in our schema,
# the model should ignore them.
# --------------------------------------------------------

text = "Hello My name is Mayank. I have an IPhone which is not working at all. Yesterday I broke it and & I live in Delhi. My Email is mayank11@gmail.com. My contact number is 9988776655."


prompt = f"""
This is the customer ticket. Please extract the personal information from this.
{text}
"""


# --------------------------------------------------------
# STEP 7: Create the Conversation
#
# Every LLM request is sent as a list of messages.
#
# Roles:
#
# System    -> Defines model behaviour.
# User      -> Contains the actual request.
# Assistant -> Generated by the model.
# --------------------------------------------------------

message = {
    "role":role,
    "content":prompt
}

messages = [message_system,message]

# --------------------------------------------------------
# STEP 8: Send Request to the LLM
#
# JSON mode ensures the response is returned as a valid
# JSON object instead of plain text.
# --------------------------------------------------------

response = client.chat.completions.create(model=model, messages=messages, response_format = response_format)



# --------------------------------------------------------
# STEP 9: Extract the JSON Response
# --------------------------------------------------------
answer = response.choices[0].message.content
print(answer)


# --------------------------------------------------------
# STEP 10: Convert JSON String into Python Dictionary
#
# json.loads() converts a JSON string into a Python dict.
#
# NOTE:
# json.load() is used for FILES.
# json.loads() is used for STRINGS.
# --------------------------------------------------------

import json 
raw_json = answer
data_file = json.loads(raw_json)


# --------------------------------------------------------
# STEP 11: Validate using Pydantic
#
# The dictionary is validated against our Ticket schema.
#
# If the JSON is missing required fields or contains
# incorrect data types, Pydantic will raise an error.
# --------------------------------------------------------

ticket = Ticket(**data_file)


# --------------------------------------------------------
# STEP 12: Access Individual Fields
#
# After validation, we can use the fields just like
# normal Python object attributes.
# --------------------------------------------------------

print(ticket.name)
print(ticket.email)
print(ticket.issue)


# --------------------------------------------------------
# Homework Idea
#
# Build an AI Resume Analyzer.
#
# Input:
#   - Resume (PDF/DOCX)
#
# Extract:
#   - Name
#   - Skills
#   - Experience
#   - Projects
#   - Education
#
# Compare the extracted information against a Job
# Description and calculate a matching percentage.
#
# Example:
#
# Match Score : 82%
# Missing Skills :
#   - Docker
#   - AWS
#
# Recommendation :
# Shortlist for Interview
#
# This is one of the most common real-world AI
# applications built using structured outputs.
# --------------------------------------------------------